name: Some Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "from job1"

  job2:
    runs-on: ubutnu-latest
    steps:
      - run: echo "hello from job2"
