name: Matrix

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo "running on ${{matrix.os}}"

  package:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "package"

    
